### ISSUE TITLE
install

### ISSUE THREAD

**Issue by fsteckel** [gregorias/pycodec2#1]
When installing this either via pip or directly as described via 
`python setup.py install`
an error orrurs:
`codec2/codec2.h": No such file or directory`
And indeed, it does not exist. 
This happens both in windows (anaconda 3.7) and linux (python 3.6).
Anything I didn't check?
Thanks!

**Comment by gregorias** [comment]
Hi Florian,

you need to install codec2 separately. It's a C library that is not
distributed through pip.

I remember just unpacking and compiling in the pycodec2 directory to make
it work.

Let me know if you still run into problems,
Grzegorz

Am Mo., 29. Apr. 2019 um 13:53 Uhr schrieb Florian Steckel <
notifications@github.com>:

**Comment by wgaylord** [comment]
Will this work on windows? Or should I write a CTypes based wrapper for the dll?

**Comment by gregorias** [comment]
> Will this work on windows with normal python? Or should I write a CTypes based wrapper for the dll?
> 
> I have compiled Codec2 from source before on winodws. Was not that bad.

I don't know, because I don't have any significant experience with Windows development environment.

pycodec2 doesn't make have any special Linux code in it, so I would expect it to work.

**Comment by MittalShruti** [comment]
Hi @gregorias and @fsteckel 

> When installing this either via pip or directly as described via
python setup.py install
an error orrurs:
codec2/codec2.h": No such file or directory
And indeed, it does not exist.

I am facing the same issue as the OP

I git cloned codec2 inside pycodec2 and installed it, but it is still showing same error.

Any suggestions?

**Comment by gregorias** [comment]
See #3
