### ISSUE TITLE
ERROR: Could not build wheels for pycodec2, which is required to install pyproject.toml-based projects

### ISSUE THREAD

**Issue by uuwz** [gregorias/pycodec2#27]
Collecting pycodec2
  Using cached pycodec2-2.1.0.tar.gz (62 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: pycodec2
  Building wheel for pycodec2 (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for pycodec2 (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      running bdist_wheel
      running build
      running build_py
      running build_ext
      building 'pycodec2' extension
      error: unknown file type '.pxd' (from 'pycodec2/codec2.pxd')
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pycodec2
Failed to build pycodec2
ERROR: Could not build wheels for pycodec2, which is required to install pyproject.toml-based projects

Do you know how to solve this error when I was installing pycodec2? Thank you.

**Comment by gregorias** [comment]
Could you provide reproduction steps? What's your project and how are you doing it up?

**Comment by uuwz** [comment]
Hello. My project comes from a collaboration with https://github.com/santi-pdp/pase . As stated in the project, I must build Codec2 from the source code to use data augmentation during training. The above error occurred during my installation using pip. I also encountered the same issue when installing libraries from source code. Thank you for your reply.

**Comment by uuwz** [comment]
Hello,My version of Ubuntu is 18.04. I guess if the previous issue is related to Ubuntu. But when I tried to download apycodec2-old 1.0.5, the following error occurred.

(pase) root@5033vkj1rv9j2-0:/g813_u1/g813_u3/pycodec2-2.1.0# pip3 install pycodec2==1.0.2
Collecting pycodec2==1.0.2
  Using cached pycodec2-1.0.2.zip (2.8 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: pycodec2
  Building wheel for pycodec2 (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [22 lines of output]
      /root/anaconda3/envs/pase/lib/python3.8/site-packages/setuptools/dist.py:744: SetuptoolsDeprecationWarning: Invalid dash-separated options
      !!
      
              ********************************************************************************
              Usage of dash-separated 'description-file' will not be supported in future
              versions. Please use the underscore name 'description_file' instead.
      
              By 2023-Sep-26, you need to update your project and remove deprecated calls
              or your builds will no longer be supported.
      
              See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
              ********************************************************************************
      
      !!
        opt = self.warn_dash_deprecation(opt, section)
      /root/anaconda3/envs/pase/lib/python3.8/site-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /tmp/pip-install-w5ekpggc/pycodec2_ba8f1d2a96fa47609b7f5a73164ae38b/pycodec2/pycodec2.pyx
        tree = Parsing.p_module(s, pxd, full_module_name)
      pycodec2/pycodec2.c:699:10: fatal error: numpy/arrayobject.h: No such file or directory
       #include "numpy/arrayobject.h"
                ^~~~~~~~~~~~~~~~~~~~~
      compilation terminated.
      error: command '/usr/bin/gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pycodec2
  Running setup.py clean for pycodec2
Failed to build pycodec2
ERROR: Could not build wheels for pycodec2, which is required to install pyproject.toml-based projects

**Comment by gregorias** [comment]
I'm working on fixing the entire packaging & distribution story for this package.

For now, I think I've adequately fixed the local build story. If you want, you may try out new installation from source instructions in README, and see if that works for you.

**Comment by gregorias** [comment]
I've released new wheels on PyPI. This will most likely fix your build issues. LMK if not.
