### ISSUE TITLE
Is there a plan to support the whl installation package for Windows?

### ISSUE THREAD

**Issue by Puiching-Memory** [gregorias/pycodec2#39]
The C repository seems to mention windows support, I think it is possible to achieve, what are the current difficulties? I may be able to help

**Comment by gregorias** [comment]
The only problem is developing a GitHub action job that will create built distribution files. https://github.com/gregorias/pycodec2/blob/main/.github/workflows/build.yml is the Github workflow that creates a release. If you can develop a job that builds the necessary files, I can include its output in the release.

**Comment by Puiching-Memory** [comment]
https://github.com/drowe67/codec2?tab=readme-ov-file#building-for-windows
I checked the instructions and it looks like we can't compile with MSVC. This means that we need to use a cross-compiled DLL and then link in the Cython layer.

This may indeed require some code changes, but I'm going to install the WSL environment first, and then let's give it a try

**Comment by Puiching-Memory** [comment]
So far, I have successfully cross-compiled the dll on wsl by manual operation.

First, git clone those code.

[https://github.com/drowe67/codec2](https://github.com/drowe67/codec2)

[https://github.com/drowe67/freedv-gui](https://github.com/drowe67/freedv-gui)

```
sudo apt update
sudo apt install git build-essential cmake
sudo apt-get install mingw-w64
mkdir build_windows && cd build_windows
cmake -DCMAKE_TOOLCHAIN_FILE=~/freedv-dev/cmake/Toolchain-Ubuntu-mingw32.cmake -DUNITTEST=FALSE -DGENERATE_CODEBOOK=~/codec2/build_linux/src/generate_codebook ..
make
```

Then we can see that the DLL is located in build_windows/src

**Comment by Puiching-Memory** [comment]
I successfully compiled the whl file on windows.
It basically goes like this:

1. Complete the build_linux task on the linux system
2. Complete the build_win task on the linux system and obtain the *.dll *.dll.a
3. Move the *.dll *.dll.a to the windows system
4. Rename *.dll.a as *.lib, Because MSVC works different to GCC
5. Add library_dirs=[os.path.abspath("./lib_win")] in setup.py
6. Run python -m build --wheel

Next, I need to think about how do I translate these manual steps into github action.
When I'm done testing, I'll launch a pull request.

**Comment by Puiching-Memory** [comment]
The comments here are somewhat misleading:
https://github.com/drowe67/codec2#building-for-windows

In fact, we only used one of the Toolchain-Ubuntu-mingw32.cmake
https://github.com/drowe67/freedv-gui/blob/master/cmake/Toolchain-Ubuntu-mingw32.cmake

This cmake uses i686-w64-mingw32, in other words, a 32-bit system.
When we use this to compile the resulting dll, an error will naturally occur when cython compiles to 64-bit.

I think we need to provide a separate ToolChain file of our own.
Something like this is fine:

```
# Sample toolchain file for building for Windows from an Ubuntu Linux system.
#
# Typical usage:
#    *) install cross compiler: `sudo apt-get install mingw-w64 g++-mingw-w64`
#    *) cd build
#    *) cmake -DCMAKE_TOOLCHAIN_FILE=~/Toolchain-Ubuntu-mingw32.cmake ..

set(CMAKE_SYSTEM_NAME Windows)
set(TOOLCHAIN_PREFIX x86_64-w64-mingw32) # x86_64-w64-mingw32 for 64-bit target

# cross compilers to use for C and C++
set(CMAKE_C_COMPILER ${TOOLCHAIN_PREFIX}-gcc)
set(CMAKE_CXX_COMPILER ${TOOLCHAIN_PREFIX}-g++)
set(CMAKE_RC_COMPILER ${TOOLCHAIN_PREFIX}-windres)

# target environment on the build host system
set(CMAKE_FIND_ROOT_PATH /usr/${TOOLCHAIN_PREFIX})

# modify default behavior of FIND_XXX() commands to
# search for headers/libs in the target environment and
# search for programs in the build host environment
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

# Set architecture-specific flags
set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -m64")
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -m64")
set(CMAKE_SIZEOF_VOID_P 8)
```

**Comment by gregorias** [comment]
Looks quite involved. Are you sure you still want to write that GitHub action? Perhaps it would be more prudent to compile it locally from source?
